import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useQuery, useMutation } from '../convex/_generated/react'
import { useCallback, useState, FormEvent } from 'react'

const Home: NextPage = () => {
  const [newQuoteText, setNewQuoteText] = useState("");
  const quotes = useQuery('getQuotes') ?? []
  const incrementVotes = useMutation('incrementVotes')
  const addQuote = useMutation('addQuote')
  //const incrementByOne = useCallback(() => increment('clicks', 1), [increment])
  async function handleAddQuote(event: FormEvent) {
    event.preventDefault();
    setNewQuoteText("");
    await addQuote(newQuoteText);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js with Convex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Quote Voter
        </h1>
        {quotes.map(({text, votes, id}) =>
          <div>
            <p className={styles.description}>
              {text}
            </p>
            {votes}
            <button className={styles.button} onClick={() => incrementVotes(id, 1)}> +1 </button>
          </div>

        )}
        <form
            onSubmit={handleAddQuote}

        >
            <input
                value={newQuoteText}
                onChange={event => setNewQuoteText(event.target.value)}
                className="form-control w-50"
                placeholder="New quote..."
            />
            <input
                type="submit"
                value="Add a quote!"
                className={styles.button}
                disabled={!newQuoteText}
            />
        </form>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.convex.dev/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/convex.svg" alt="Convex Logo" width={90} height={18} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
