import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useQuery, useMutation } from '../convex/_generated/react'
import { Id } from "../convex/_generated/dataModel";

import { useEffect, useState, FormEvent } from 'react'
import { useAuth0 } from '@auth0/auth0-react';
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import 'react-tabs/style/react-tabs.css';
import QuoteVoter from "../components/quoteVoter";
import GoatVoter from "../components/goatVoter";
import NoteVoter from '../components/noteVoter'
import BoatVoter from '../components/boatVoter'

const Home: NextPage = () => {

  const [userId, setUserId] = useState<Id<"users"> | null>(null);
  const storeUser = useMutation("storeUser");
  useEffect(() => {
    // Store the user in the database.
    // Recall that `storeUser` gets the user information via the `auth`
    // object on the server. You don't need to pass anything manually here.
    async function createUser() {
      const id = await storeUser();
      setUserId(id);
    }
    createUser();
    return () => setUserId(null);
  }, [storeUser]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Upvoter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Tabs>
          <TabList>
            <Tab>Quotes</Tab>
            <Tab>Goats</Tab>
            <Tab>Notes</Tab>
            <Tab>Boats</Tab>
          </TabList>
          <TabPanel>
            <QuoteVoter/>
          </TabPanel>
          <TabPanel>
            {userId && <GoatVoter userId={userId}/>}
          </TabPanel>
          <TabPanel>
            <NoteVoter/>
          </TabPanel>
          <TabPanel>
            <BoatVotingTabs/>
          </TabPanel>
        </Tabs>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.convex.dev/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/convex.svg" alt="Convex Logo" width={90} height={18} />
          </span>
        </a>
        <div className="text-center">
          <span>
            <Logout />
          </span>
        </div>
      </footer>
    </div>
  )
}

export function BoatVotingTabs() {
  return <Tabs defaultIndex={1}>
    <TabList>
      <Tab>No indices - full table scans</Tab>
      <Tab>Use indices</Tab>
      <Tab>Process boatVotes in typescript</Tab>
    </TabList>
    <TabPanel>
      <BoatVoter
        title={'Naive boat'}
        getBoats={() => useQuery('getBoats') ?? []}
      />
    </TabPanel>
    <TabPanel>
      <BoatVoter
        title={'(With indexed queries) boat'}
        getBoats={() => useQuery('getBoatsWithIndices') ?? []}
      />
    </TabPanel>
    <TabPanel>
      <BoatVoter
        title={'Typescript boat'}
        getBoats={() => useQuery('getBoatsInTypescript') ?? []}
      />
    </TabPanel>
  </Tabs>
}

export function Login() {
  const { isLoading, loginWithRedirect } = useAuth0();
  if (isLoading) {
    return <button className="btn btn-primary">Loading...</button>;
  }
  return (
    <main className="py-4">
      <h1 className="text-center">Convex Chat</h1>
      <div className="text-center">
        <span>
          <button className="btn btn-primary" onClick={loginWithRedirect}>
            Log in
          </button>
        </span>
      </div>
    </main>
  );
}

function Logout() {
  const { logout, user } = useAuth0();
  const generateData = useMutation("generateData");

  return (
    <div>
      {/* We know this component only renders if the user is logged in. */}
      <p>Logged in{user!.name ? ` as ${user!.name}` : ""}</p>
      <button
        className="btn btn-primary"
        onClick={() => logout({ returnTo: window.location.origin })}
      >
        Log out
      </button>
      <button onClick={() => generateData()}>
        Generate test data
      </button>

    </div>
  );
}

export default Home
